repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check
        language: system
        files: ^(src/|tests/).*\.py$
        types: [python]
      
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        files: ^(src/|tests/).*\.py$
        pass_filenames: false
        types: [python]

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        files: ^(src/|tests/).*\.py$
        types: [python]

      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        language: system
        files: ^(src/|tests/).*\.py$
        types: [python]

